// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbrrcxepabpxnxvbzrsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicnJjeGVwYWJweG54dmJ6cnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDg2MTIsImV4cCI6MjA3MjcyNDYxMn0.xYm2ha11VbfWJ5gHDRJJr0FxRT2lazxyKCF0MR8_G6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});